version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports: 
      - "5432:5432"
    volumes: 
      - /data/pgdata:/data/pgdata
    env_file:
      - .env
    networks:
      - web

  online-payment:
    depends_on:
      - postgres
    container_name: online-payment
    build: .
    volumes:
      - ./:/usr/src/index
    ports:
      - '5000:5000'
    command: npm run start:dev
    networks:
      - web   
    restart: on-failure

  pgadmin:
    container_name: pgadmin
    links: 
      - postgres
    image: dpage/pgadmin:latest
    ports:
     - '8080:80'
    volumes:
     - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - web

networks:
  web:
    driver: bridge
